=== shakti-096/kyc-api-spec-poc/src/main/resources/schemas/body/update-customer-kyc-info-request-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "legalID1": {
      "type": "string"
    },
    "legalIssueDate1": {
      "type": "string"
    },
    "legalExpiryDate1": {
      "type": "string"
    },
    "legalID2": {
      "type": "string"
    },
    "legalIssueDate2": {
      "type": "string"
    },
    "legalExpiryDate2": {
      "type": "string"
    },
    "residence": {
      "type": "string"
    },
    "townCountry1": {
      "type": "string"
    },
    "townCountry2": {
      "type": "string"
    },
    "streetName1": {
      "type": "string"
    },
    "streetName2": {
      "type": "string"
    },
    "phoneNumber1": {
      "type": "string"
    },
    "phoneNumber2": {
      "type": "string"
    },
    "phoneNumber3": {
      "type": "string"
    },
    "occupation1": {
      "type": "string"
    },
    "occupation2": {
      "type": "string"
    },
    "occupation3": {
      "type": "string"
    },
    "employersName1": {
      "type": "string"
    },
    "employersName2": {
      "type": "string"
    },
    "employersName3": {
      "type": "string"
    },
    "otherNationality1": {
      "type": "string"
    },
    "otherNationality2": {
      "type": "string"
    },
    "workingCountry": {
      "type": "string"
    },
    "residentStatus": {
      "type": "string"
    },
    "politicallyExposedPerson": {
      "type": "string",
      "enum": [
        "Y",
        "N"
      ]
    },
    "workingCity": {
      "type": "string"
    },
    "workingStreetName": {
      "type": "string"
    },
    "annualSalary": {
      "type": "string"
    },
    "otherSourceOfIncome": {
      "type": "string"
    },
    "accountBeneficiary": {
      "type": "string"
    },
    "beneficiaryName": {
      "type": "string"
    }
  }
}

=== shakti-096/kyc-api-spec-poc/src/main/resources/examples/body/update-customer-kyc-info-request-ex.json
{
  "legalID1": "BCG80726",
  "legalIssueDate1": "20161227",
  "legalExpiryDate1": "20261226",
  "legalID2": "BCG80727",
  "legalIssueDate2": "20161227",
  "legalExpiryDate2": "20261225",
  "residence": "",
  "townCountry1": "TEST",
  "townCountry2": "عمان الغريبة",
  "streetName1": "TEST",
  "streetName2": "عمان الغريبة",
  "phoneNumber1": "+971555259447",
  "phoneNumber2": "+971555259448",
  "phoneNumber3": "+971555259449",
  "occupation1": "OCC1",
  "occupation2": "OCC2",
  "occupation3": "OCC3",
  "employersName1": "TEST1",
  "employersName2": "TEST2",
  "employersName3": "TEST3",
  "otherNationality1": "JO",
  "otherNationality2": "US",
  "workingCountry": "JO",
  "residentStatus": "YES",
  "politicallyExposedPerson": "N",
  "accountBeneficiary": "John Smitt",
  "beneficiaryName": "John Smitt",
  "workingCity": "Baghdad",
  "workingStreetName": "",
  "annualSalary": "12",
  "otherSourceOfIncome": "Mum"
}
